title: Alagar Biotech Product Pvt Ltd
email: alagarbioteches091@gmail.com
description: 
  This is the official website for Alagar Biotech Product Private Limited

baseurl: "/" # the subpath of your site, e.g. /blog
twitter_username: alagarbiotech
github_username:  Muthubioinfo

# Build settings
theme: cayman
plugins:
- jekyll-feed # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
